
---
apiVersion: v1
kind: Namespace
metadata:
    name: boutique-v0-10-5 

---
apiVersion: v1
kind: Service
metadata:
    name: redis-cart
    namespace: boutique-v0-10-5
spec:
    selector:
        app: redis-cart
    ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-cart
    namespace: boutique-v0-10-5
    labels:
        app: redis-cart
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis-cart
    template:
        metadata:
            labels:
                app: redis-cart
        spec:
            containers:
            - name: redis-cart
              image: redis
              imagePullPolicy: Always
              ports:
              - containerPort: 6379

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cartservice
    namespace: boutique-v0-10-5
    labels:
        app: cartservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cartservice
    template:
        metadata:
            labels:
                app: cartservice
        spec:
            containers:
            - name: cartservice
              image: docker.io/alkol/cartservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 7070

---
apiVersion: v1
kind: Service
metadata:
    name: cartservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: cartservice
    ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: boutique-v0-10-5
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
            - name: frontend
              image: docker.io/alkol/frontend-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: boutique-v0-10-5
spec:
    selector:
        app: frontend
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productcatalogservice
    namespace: boutique-v0-10-5
    labels:
        app: productcatalogservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: productcatalogservice
    template:
        metadata:
            labels:
                app: productcatalogservice
        spec:
            containers:
            - name: productcatalogservice
              image: docker.io/alkol/productcatalogservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 3550

---
apiVersion: v1
kind: Service
metadata:
    name: productcatalogservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: productcatalogservice
    ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: currencyservice
    namespace: boutique-v0-10-5
    labels:
        app: currencyservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: currencyservice
    template:
        metadata:
            labels:
                app: currencyservice
        spec:
            containers:
            - name: currencyservice
              image: docker.io/alkol/currencyservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
    name: currencyservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: currencyservice
    ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    namespace: boutique-v0-10-5
    labels:
        app: paymentservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: paymentservice
    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
            - name: paymentservice
              image: docker.io/alkol/paymentservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
    name: paymentservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: paymentservice
    ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: shippingservice
    namespace: boutique-v0-10-5
    labels:
        app: shippingservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: shippingservice
    template:
        metadata:
            labels:
                app: shippingservice
        spec:
            containers:
            - name: shippingservice
              image: docker.io/alkol/shippingservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
    name: shippingservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: shippingservice
    ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: emailservice
    namespace: boutique-v0-10-5
    labels:
        app: emailservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: emailservice
    template:
        metadata:
            labels:
                app: emailservice
        spec:
            containers:
            - name: emailservice
              image: docker.io/alkol/emailservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: emailservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: emailservice
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: checkoutservice
    namespace: boutique-v0-10-5
    labels:
        app: checkoutservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: checkoutservice
    template:
        metadata:
            labels:
                app: checkoutservice
        spec:
            containers:
            - name: checkoutservice
              image: docker.io/alkol/checkoutservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
    name: checkoutservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: checkoutservice
    ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: recommendationservice
    namespace: boutique-v0-10-5
    labels:
        app: recommendationservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: recommendationservice
    template:
        metadata:
            labels:
                app: recommendationservice
        spec:
            containers:
            - name: recommendationservice
              image: docker.io/alkol/recommendationservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: recommendationservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: recommendationservice
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: adservice
    namespace: boutique-v0-10-5
    labels:
        app: adservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: adservice
    template:
        metadata:
            labels:
                app: adservice
        spec:
            containers:
            - name: adservice
              image: docker.io/alkol/adservice-v0.10.5:487d3cd
              imagePullPolicy: Always
              ports:
              - containerPort: 9555

---
apiVersion: v1
kind: Service
metadata:
    name: adservice
    namespace: boutique-v0-10-5
spec:
    selector:
        app: adservice
    ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
