
commonEnvVars:
    AD_SERVICE_ADDR: "adservice:9555"
    CART_SERVICE_ADDR: "cartservice:7070"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    EMAIL_SERVICE_ADDR: "emailservice:8080"
    FRONTEND_SERVICE_ADDR: "frontend:8080"
    PAYMENT_SERVICE_ADDR: "paymentservice:50051"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8080"
    REDIS_ADDR: "redis-cart:6379"
    ENABLE_SHOPPING_ASSISTANT: false
    DISABLE_PROFILER: 1
    DISABLE_TRACING: 1
    DISABLE_DEBUGGER: 1
    GCP_PROJECT: "hello"
    GOOGLE_CLOUD_PROJECT: "jello" 

cartservice:
    name: cartservice
    image: docker.io/alkol/cartservice-v0.10.5:36749c5
    port: 7070 
